Goals Add On Update
strangerstudios/pmpro-goals pull request #18
Opened 2023-05-10 16:14 UTC by MaximilianoRicoTabo

* Update NPM WP Scripts version to match current PMPro version
 * Add further Sales option in block side, available in the back but not in the front.
 * Refactor if/elseif/else for goal_type.
 * Rephrase hash to get rid MD5 and build a key given the passed fields.

2023-05-16 13:33 UTC, MaximilianoRicoTabo commented
@dparker1005  i have this other  PR https://github.com/MaximilianoRicoTabo/pmpro-goals/pull/1 that comes next to this one.

2023-05-16 18:47 UTC, dparker1005 requested changes
Only did a pass of the `pmpro-goals.php` file so far. Still need to look at the JS updates once these changes are made

2023-05-16 18:47 UTC, dparker1005 commented on pmpro-goals.php
> +	$goal_reached = false;
```suggestion
```
This variable is never used.

2023-05-16 18:54 UTC, MaximilianoRicoTabo commented on pmpro-goals.php
> +		$level_data = implode(",", wp_list_pluck($levels, 'label'));
the thing is that select2 select send the data as multi dimensional array, that's why i change that. Perhaps you're not seeing that change in the gutenberg  side somehow ?

2023-05-16 18:59 UTC, MaximilianoRicoTabo commented on pmpro-goals.php
> +	if (! $total && $total !== 0) {
i was trying to use a falsy condition then found about 0 edge case. i need to revisit but it might be possible to do it as you say

2023-05-16 19:09 UTC, dparker1005 commented on pmpro-goals.php
> +		$level_data = implode(",", wp_list_pluck($levels, 'label'));
Thanks for explaining that. The site that I am testing on already had the Goals Add On set up, and previous setups will be passing `$levels` as an array of level IDs. We need to continue supporting those existing setups. Would it be possible to update the block to only save level IDs even though the field is collecting data in a select2?

If not, we will need to get more clever here and use `wp_list_pluck` only when `$levels` is not an array of `int`s

2023-05-23 17:43 UTC, MaximilianoRicoTabo commented on pmpro-goals.php
> +		$level_data = implode(",", wp_list_pluck($levels, 'label'));
Tried to handle from client side but after a while struggling with it with no lucky decided to to manage in the PHP side which is way easier.

2023-05-23 17:46 UTC, MaximilianoRicoTabo commented on pmpro-goals.php
> +	if (! $total && $total !== 0) {
finally did this way, let me know if you have further thoughts on this and we change if you want.
```
$should_set_new_transient = $total == false || intval($total) == 0;
if ($should_set_new_transient)	 {
```

2023-05-23 17:46 UTC, MaximilianoRicoTabo commented on pmpro-goals.php
> +				$sql = "SELECT total FROM $wpdb->pmpro_membership_orders WHERE membership_id IN(" . $level_data . ") AND status = 'success'";
done, thanks.

2023-05-23 17:46 UTC, MaximilianoRicoTabo commented on pmpro-goals.php
> +				$sql .= " AND timestamp <= '" . esc_sql($end_date) . "'";
done. Thanks for clarifying this in slack.

2023-05-23 17:47 UTC, MaximilianoRicoTabo commented on pmpro-goals.php
> +	$after_total_amount_text .= '<span class="pmpro_goals-goal">' . $formated_goal . '</span>';
d'oh. Done

2023-05-23 17:47 UTC, MaximilianoRicoTabo commented on pmpro-goals.php
> +	$goal_reached = false;
removed.

2023-06-08 10:14 UTC, merged